#! /usr/bin/env bash
set -eu

if [[ $# -eq 0 ]]; then
  echo "Usage: imp CONFIG_FILE"
  echo ""
  echo "Missing CONFIG_FILE. Check https://gitlab.izsvenezie.it/biv/analysis_pipelines/imp for more information."
  exit 1
fi

config=$1

workdir="$(pwd | sed 's#/pbs/data/#/pbs/scratch/#')"
export NXF_LOG_FILE="$workdir/.nextflow.log"
export NXF_CACHE_DIR="$workdir/.nextflow"
export NXF_WORK="$workdir/work"

# resolve path to this script https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
nextflow_workflow="$DIR/src/main.nf"

module load nextflow >/dev/null
$nextflow_workflow -c $config -profile bivfe -resume
